/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartplanner;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kerbag and Douglas
 */
public class signIn extends javax.swing.JFrame {
        Connectivity c = new Connectivity();
    /**
     * Creates new form logIn
     */
    public signIn() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        signInPasswordTextField = new javax.swing.JPasswordField();
        signInButton = new javax.swing.JButton();
        signUpText = new javax.swing.JLabel();
        signInEmailTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Sign In");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 150, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Email");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 150, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Password");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 150, 30));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 270, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 270, 30));

        signInPasswordTextField.setBackground(new java.awt.Color(0, 0, 51));
        signInPasswordTextField.setForeground(new java.awt.Color(255, 255, 255));
        signInPasswordTextField.setText("Eahabebe12");
        signInPasswordTextField.setBorder(null);
        signInPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInPasswordTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(signInPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 270, 30));

        signInButton.setBackground(new java.awt.Color(0, 153, 153));
        signInButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        signInButton.setForeground(new java.awt.Color(255, 255, 255));
        signInButton.setText("Sign In");
        signInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInButtonMouseClicked(evt);
            }
        });
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        jPanel2.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 140, 50));

        signUpText.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        signUpText.setForeground(new java.awt.Color(255, 255, 255));
        signUpText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpText.setText("Sign Up");
        signUpText.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        signUpText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpTextMouseClicked(evt);
            }
        });
        jPanel2.add(signUpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 140, 30));

        signInEmailTextField.setBackground(new java.awt.Color(0, 0, 51));
        signInEmailTextField.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        signInEmailTextField.setForeground(new java.awt.Color(255, 255, 255));
        signInEmailTextField.setText("kerbag@gmail.com");
        signInEmailTextField.setBorder(null);
        signInEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInEmailTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(signInEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 270, 30));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Smart Planner");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smartplanner/Calender.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 310, 270));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tasks & Events");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 150, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 270, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 450));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signInPasswordTextFieldActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signInButtonActionPerformed

    private void signInEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signInEmailTextFieldActionPerformed

    private void signUpTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpTextMouseClicked
        // TODO add your handling code here:
        signUp obj2 = new signUp();
        obj2.setVisible(true);
        dispose();
    }//GEN-LAST:event_signUpTextMouseClicked

    private void signInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInButtonMouseClicked
        // TODO add your handling code here:
        String email = signInEmailTextField.getText();
        String password = String.valueOf(signInPasswordTextField.getPassword());
        if(c.login(email, password)){
            String[] args = {email};
            try {
                SmartPlanner.main(args);
            } catch (NoSuchFieldException ex) {
                Logger.getLogger(signIn.class.getName()).log(Level.SEVERE, null, ex);
            }
            dispose();
        }else{
            System.out.print("Incorrect Email or Password");
        }

    }//GEN-LAST:event_signInButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new signIn().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton signInButton;
    private javax.swing.JTextField signInEmailTextField;
    private javax.swing.JPasswordField signInPasswordTextField;
    private javax.swing.JLabel signUpText;
    // End of variables declaration//GEN-END:variables
}
